In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')  # enable import from src/

In [2]:
import pickle

from src.net import InstanceGCN
from src.utils import load_from_wandb

with open('../study3.pkl', 'rb') as f:
    study = pickle.load(f)

study

In [3]:
df = study.trials_dataframe()
df

number     value             datetime_start          datetime_complete  \
0        0 -0.501405 2023-02-28 19:08:56.949504 2023-02-28 19:13:11.180673   
1        1 -0.730518 2023-02-28 19:13:11.181271 2023-02-28 21:18:45.254314   
2        2 -0.731336 2023-02-28 21:18:45.255068 2023-02-28 21:56:42.915831   
3        3 -0.554607 2023-02-28 21:56:42.916618 2023-02-28 21:58:19.864102   
4        4 -0.749141 2023-02-28 21:58:19.864964 2023-02-28 22:07:25.358250   
5        5 -0.519052 2023-02-28 22:07:25.359084 2023-02-28 22:19:51.331823   
6        6 -0.500013 2023-02-28 22:19:51.334488 2023-02-28 22:23:45.049165   
7        7 -0.656207 2023-02-28 22:23:45.050001 2023-02-28 22:27:37.844437   
8        8 -0.789749 2023-02-28 22:27:37.845409 2023-02-28 22:52:56.093719   
9        9 -0.729719 2023-02-28 22:52:56.094621 2023-02-28 23:25:39.632961   
10      10 -0.750704 2023-02-28 23:25:39.633889 2023-02-28 23:59:56.917969   
11      11 -0.735039 2023-02-28 23:59:56.918955 2023-03-01 00:34:16.079417   
12      12 -0.744119 2023-03-01 00:34:16.080345 2023-03-01 01:08:29.303988   
13      13 -0.772617 2023-03-01 01:08:29.304913 2023-03-01 03:13:57.810787   
14      14 -0.730404 2023-03-01 03:13:57.811673 2023-03-01 05:19:08.533403   
15      15 -0.747198 2023-03-01 05:19:08.534369 2023-03-01 06:34:00.397554   
16      16 -0.732096 2023-03-01 06:34:00.398538 2023-03-01 08:35:49.825184   
17      17 -0.786963 2023-03-01 08:35:49.826131 2023-03-01 09:12:23.204464   
18      18 -0.762318 2023-03-01 09:12:23.205413 2023-03-01 09:30:55.577748   
19      19 -0.729193 2023-03-01 09:30:55.578720 2023-03-01 10:08:58.897114   
20      20 -0.768169 2023-03-01 10:08:58.898292 2023-03-01 10:16:24.592334   
21      21 -0.752040 2023-03-01 21:58:34.979346 2023-03-02 00:14:59.665675   
22      22 -0.748165 2023-03-02 00:14:59.666666 2023-03-02 01:00:54.971595   
23      23 -0.766071 2023-03-02 01:00:54.972428 2023-03-02 03:08:55.884248   
24      24 -0.729657 2023-03-02 03:08:55.885110 2023-03-02 03:54:45.198992   
25      25 -0.636144 2023-03-02 03:54:45.199971 2023-03-02 04:11:47.272159   
26      26 -0.760368 2023-03-02 04:11:47.273047 2023-03-02 06:01:02.795264   
27      27 -0.784472 2023-03-02 06:01:02.796290 2023-03-02 06:21:04.956281   
28      28 -0.770285 2023-03-02 06:21:04.957257 2023-03-02 06:30:05.124312   
29      29 -0.716593 2023-03-02 06:30:05.125287 2023-03-02 06:47:53.197535   
30      30 -0.774630 2023-03-02 06:47:53.198603 2023-03-02 07:04:13.234400   
31      31 -0.774630 2023-03-02 07:04:13.235446 2023-03-02 07:20:33.153250   
32      32 -0.784594 2023-03-02 07:20:33.154464 2023-03-02 07:28:49.108989   
33      33 -0.757287 2023-03-02 07:28:49.110054 2023-03-02 07:36:38.073272   
34      34 -0.751246 2023-03-02 07:36:38.074370 2023-03-02 07:40:50.679096   
35      35 -0.749045 2023-03-02 07:40:50.680196 2023-03-02 07:56:14.623857   
36      36 -0.765996 2023-03-02 07:56:14.624966 2023-03-02 08:04:08.491451   
37      37 -0.723003 2023-03-02 08:04:08.492544 2023-03-02 08:08:07.995534   
38      38 -0.749141 2023-03-02 08:08:07.996629 2023-03-02 08:20:57.987825   
39      39 -0.714579 2023-03-02 08:20:57.988951 2023-03-02 08:38:33.462814   
40      40 -0.762096 2023-03-02 08:38:33.463955 2023-03-02 08:52:46.049384   
41      41 -0.774630 2023-03-02 08:52:46.050526 2023-03-02 09:09:05.897780   
42      42 -0.774630 2023-03-02 09:09:05.898939 2023-03-02 09:25:28.161041   
43      43 -0.500640 2023-03-02 09:25:28.162275 2023-03-02 09:32:46.140431   
44      44 -0.756354 2023-03-03 08:12:06.636129 2023-03-03 08:28:25.150899   
45      45 -0.765448 2023-03-03 08:28:25.151850 2023-03-03 08:31:59.800590   
46      46 -0.741675 2023-03-03 13:16:47.673214 2023-03-03 13:50:32.408425   
47      47 -0.731247 2023-03-03 13:50:32.409548 2023-03-03 13:54:44.006719   

                 duration params_SAGE_aggregator_type  params_SAGE_feat_drop  \
0  0 days 00:04:14.231169                         NaN                    NaN   
1  0 days 02:05:34.07

In [5]:
study.best_trial

FrozenTrial(number=8, state=TrialState.COMPLETE, values=[-0.7897487784579038], datetime_start=datetime.datetime(2023, 2, 28, 22, 27, 37, 845409), datetime_complete=datetime.datetime(2023, 2, 28, 22, 52, 56, 93719), params={'conv1': 'GraphConv', 'conv2': 'SAGEConv', 'SAGE_aggregator_type': 'pool', 'SAGE_feat_drop': 0.09088315812338871, 'conv3': 'GraphConv', 'n_h_feats': 19, 'single_conv_for_both_passes': False, 'n_passes': 1, 'batch_power': 2, 'samples_per_problem_power': 9}, user_attrs={'wandb_id': '4qwwaeyy'}, system_attrs={}, intermediate_values={}, distributions={'conv1': CategoricalDistribution(choices=('GraphConv', 'SAGEConv')), 'conv2': CategoricalDistribution(choices=(None, 'GraphConv', 'SAGEConv')), 'SAGE_aggregator_type': CategoricalDistribution(choices=('pool', 'gcn', 'lstm')), 'SAGE_feat_drop': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'conv3': CategoricalDistribution(choices=(None, 'GraphConv', 'SAGEConv')), 'n_h_feats': IntDistribution(high=20, log=False,

In [10]:
study.best_trial.user_attrs

{'wandb_id': '4qwwaeyy'}

In [11]:
study.best_params

{'conv1': 'GraphConv',
 'conv2': 'SAGEConv',
 'SAGE_aggregator_type': 'pool',
 'SAGE_feat_drop': 0.09088315812338871,
 'conv3': 'GraphConv',
 'n_h_feats': 19,
 'single_conv_for_both_passes': False,
 'n_passes': 1,
 'batch_power': 2,
 'samples_per_problem_power': 9}

In [18]:
df.loc[45:51]

number     value             datetime_start          datetime_complete  \
45      45  0.405158 2023-02-25 17:51:53.733083 2023-02-25 18:53:52.211798   
46      46  0.424943 2023-02-25 18:53:52.213505 2023-02-25 19:55:10.816302   
47      47  0.681222 2023-02-25 19:55:10.816762 2023-02-25 20:39:56.081809   
48      48  0.467211 2023-02-25 20:39:56.083537 2023-02-25 21:46:10.688776   
49      49  0.371935 2023-02-25 21:46:10.689221 2023-02-25 22:47:29.378206   
50      50  0.679754 2023-02-25 22:47:29.379969 2023-02-25 22:50:38.121264   
51      51  0.366804 2023-02-25 22:50:38.121680 2023-02-25 23:51:54.721814   

                 duration params_SAGE_aggregator_type  params_SAGE_feat_drop  \
45 0 days 01:01:58.478715                        lstm               0.199043   
46 0 days 01:01:18.602797                        lstm               0.188482   
47 0 days 00:44:45.265047                        lstm               0.193554   
48 0 days 01:06:14.605239                        lstm               0.170385   
49 0 days 01:01:18.688985                        lstm               0.136444   
50 0 days 00:03:08.741295                         NaN                    NaN   
51 0 days 01:01:16.600134                        lstm               0.126652   

    params_batch_power params_conv1 params_conv2 params_conv3  \
45                   4     SAGEConv         None         None   
46                   5     SAGEConv         None         None   
47                   4     SAGEConv    GraphConv         None   
48                   4     SAGEConv         None         None   
49                   5     SAGEConv         None         None   
50                   6    GraphConv         None         None   
51                   5     SAGEConv         None         None   

    params_n_h_feats  params_n_passes  params_samples_per_problem_power  \
45                12                2                                 8   
46                12                2                                 9   
47                10                2                                 8   
48                 7                2                                 9   
49                12                2                                 8   
50                13                2                                 8   
51                12                2                                 8   

    params_single_conv_for_both_passes     state  
45                                True  COMPLETE  
46                                True  COMPLETE  
47                                True  COMPLETE  
48                                True  COMPLETE  
49                               False  COMPLETE  
50                               False  COMPLETE  
51                               False  COMPLETE

In [21]:
df['params_n_h_feats'].value_counts()

12    11
14     8
13     8
9      7
8      6
18     6
11     5
10     5
15     4
17     4
20     3
6      3
16     3
7      3
5      2
19     2
3      1
2      1
Name: params_n_h_feats, dtype: int64

In [10]:
2**5

32

In [27]:
net = InstanceGCN(
    2,
    n_h_feats=9,
    single_conv_for_both_passes=True,
    n_passes=2,
    conv1='SAGEConv',
    conv1_kwargs={
        'aggregator_type': 'lstm',
        'feat_drop': 0.1,
    },
    conv2='SAGEConv',
    conv2_kwargs={
        'aggregator_type': 'lstm',
        'feat_drop': 0.1,
    },
    conv3='SAGEConv',
    conv3_kwargs={
        'aggregator_type': 'lstm',
        'feat_drop': 0.1,
    },
    readout_op=None,
)
net = load_from_wandb(net, 'h1mxte3m', 'sat-gnn', 'model_last')

In [29]:
import torch

def downscale_weights(module):
    if isinstance(module, torch.nn.Linear):
        module.weight.data /= 10

net.apply(downscale_weights)

InstanceGCN(
  (soc_emb): Sequential(
    (0): Linear(in_features=1, out_features=9, bias=True)
    (1): ReLU()
  )
  (var_emb): Sequential(
    (0): Linear(in_features=2, out_features=9, bias=True)
    (1): ReLU()
  )
  (con_emb): Sequential(
    (0): Linear(in_features=2, out_features=9, bias=True)
    (1): ReLU()
  )
  (convs): Sequential(
    (0): HeteroGraphConv(
      (mods): ModuleDict(
        (v2c): SAGEConv(
          (feat_drop): Dropout(p=0.1, inplace=False)
          (lstm): LSTM(9, 9, batch_first=True)
          (fc_neigh): Linear(in_features=9, out_features=9, bias=False)
          (fc_self): Linear(in_features=9, out_features=9, bias=True)
        )
        (s2c): SAGEConv(
          (feat_drop): Dropout(p=0.1, inplace=False)
          (lstm): LSTM(9, 9, batch_first=True)
          (fc_neigh): Linear(in_features=9, out_features=9, bias=False)
          (fc_self): Linear(in_features=9, out_features=9, bias=True)
        )
        (c2v): SAGEConv(
          (feat_drop): D

In [31]:
from pathlib import Path
instances_fpaths = [fp for fp in Path('../data/raw/').glob('97_9*.jl')]
instances_fpaths = sorted(instances_fpaths)
instances_fpaths

[PosixPath('../data/raw/97_9.jl'),
 PosixPath('../data/raw/97_9_1.jl'),
 PosixPath('../data/raw/97_9_10.jl'),
 PosixPath('../data/raw/97_9_11.jl'),
 PosixPath('../data/raw/97_9_12.jl'),
 PosixPath('../data/raw/97_9_13.jl'),
 PosixPath('../data/raw/97_9_14.jl'),
 PosixPath('../data/raw/97_9_15.jl'),
 PosixPath('../data/raw/97_9_16.jl'),
 PosixPath('../data/raw/97_9_17.jl'),
 PosixPath('../data/raw/97_9_18.jl'),
 PosixPath('../data/raw/97_9_19.jl'),
 PosixPath('../data/raw/97_9_2.jl'),
 PosixPath('../data/raw/97_9_20.jl'),
 PosixPath('../data/raw/97_9_3.jl'),
 PosixPath('../data/raw/97_9_4.jl'),
 PosixPath('../data/raw/97_9_5.jl'),
 PosixPath('../data/raw/97_9_6.jl'),
 PosixPath('../data/raw/97_9_7.jl'),
 PosixPath('../data/raw/97_9_8.jl'),
 PosixPath('../data/raw/97_9_9.jl')]

# Test

In [17]:
from src.problem import old_load_data, oracle

with open('../data/processed/resultados_0.pkl', 'rb') as f:
    rs = pickle.load(f)

with open('../data/processed/objetivos_0.pkl', 'rb') as f:
    os = pickle.load(f)

In [27]:
model = oracle(0, '../data/raw/97_9.jl')

for r, o in zip(rs, os):
    for i in range(len(r)):
        model.getVars()[i].ub = r[i]
        model.getVars()[i].lb = r[i]

    model.optimize()
    if model.status == 2 and o < 0:
        print('FOUND')
        break
    elif model.status != 2 and o > 0:
        print('FOUND too')
        break

In [47]:
with open('../ds.pkl', 'rb') as f:
    ds_old = pickle.load(f)
with open('../ds_new.pkl', 'rb') as f:
    var_features, con_features = pickle.load(f)
var_features, con_features

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]], device='cuda:0', dtype=torch.float64),
 tensor([[0.],
         [0.],
         [2.],
         ...,
         [0.],
         [0.],
         [0.]], device='cuda:0', dtype=torch.float64))

In [49]:
var_features.shape

torch.Size([6208, 2])

In [46]:
ds_old[1][0].nodes['var'].data['x'] == ds_new[1][0].nodes['var'].data['x']

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=torch.float64)