In [14]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')  # enable import from src/

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
from pathlib import Path

import torch
import matplotlib.pyplot as plt
from dgl.dataloading import GraphDataLoader

from src.dataset import MultiTargetDataset, OptimalsDataset
from src.net import InstanceGCN

In [18]:
instances_fps = list(Path('../data/raw/').glob('97_9_*.json'))

ds = OptimalsDataset(instances_fps[:5])
ds[0]

(Graph(num_nodes={'con': 5530, 'soc': 291, 'var': 1746},
       num_edges={('con', 'c2s', 'soc'): 775, ('con', 'c2v', 'var'): 61390, ('soc', 's2c', 'con'): 775, ('var', 'v2c', 'con'): 61390},
       metagraph=[('con', 'soc', 'c2s'), ('con', 'var', 'c2v'), ('soc', 'con', 's2c'), ('var', 'con', 'v2c')]),
 array([1., 1., 1., ..., 0., 0., 0.]))

In [3]:
instances_fps = list(Path('../data/raw/').glob('97_9_*.json'))

ds = MultiTargetDataset(instances_fps[:5], sols_dir='../data/interim/', return_model=True)

g, ys, m = ds[0]
g, ys, m

Set parameter Username
Academic license - for non-commercial use only - expires 2024-02-10


(Graph(num_nodes={'con': 5530, 'soc': 291, 'var': 1746},
       num_edges={('con', 'c2s', 'soc'): 775, ('con', 'c2v', 'var'): 61390, ('soc', 's2c', 'con'): 775, ('var', 'v2c', 'con'): 61390},
       metagraph=[('con', 'soc', 'c2s'), ('con', 'var', 'c2v'), ('soc', 'con', 's2c'), ('var', 'con', 'v2c')]),
 (array([[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]]),
  array([2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
         2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
         2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
         2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
         2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
         2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627., 2627.,
        

In [13]:
m.Params.Presolve

-1

In [14]:
net = InstanceGCN(1, readout_op=None)

net

InstanceGCN(
  (soc_emb): Sequential(
    (0): Linear(in_features=1, out_features=10, bias=True)
    (1): ReLU()
  )
  (var_emb): Sequential(
    (0): Linear(in_features=1, out_features=10, bias=True)
    (1): ReLU()
  )
  (con_emb): Sequential(
    (0): Linear(in_features=2, out_features=10, bias=True)
    (1): ReLU()
  )
  (convs): Sequential(
    (0): HeteroGraphConv(
      (mods): ModuleDict(
        (v2c): GraphConv(in=10, out=10, normalization=both, activation=None)
        (s2c): GraphConv(in=10, out=10, normalization=both, activation=None)
        (c2v): GraphConv(in=10, out=10, normalization=both, activation=None)
        (c2s): GraphConv(in=10, out=10, normalization=both, activation=None)
      )
    )
    (1): HeteroGraphConv(
      (mods): ModuleDict(
        (v2c): GraphConv(in=10, out=10, normalization=both, activation=None)
        (s2c): GraphConv(in=10, out=10, normalization=both, activation=None)
        (c2v): GraphConv(in=10, out=10, normalization=both, activation=N

In [62]:
g, (sols, objs) = ds[3]

y = torch.from_numpy(sols)[:,:2522]
w = torch.from_numpy(objs)
w = torch.softmax(w / w.max(), 0)

logits = net(g)
logits = logits.repeat((y.shape[0], 1))

# bce = torch.nn.BCEWithLogitsLoss(w)
bce = torch.nn.BCEWithLogitsLoss(reduction='none')
loss = bce(logits, y)

loss = w @ loss.sum(-1)

loss

tensor(1913.8787, dtype=torch.float64, grad_fn=<DotBackward0>)

In [66]:
dl = GraphDataLoader(ds, batch_size=1)

dl

In [70]:
g, (y, w) = next(iter(dl))
g, y, w

(Graph(num_nodes={'con': 14040, 'soc': 291, 'var': 4656},
       num_edges={('con', 'c2s', 'soc'): 775, ('con', 'c2v', 'var'): 163371, ('soc', 's2c', 'con'): 775, ('var', 'v2c', 'con'): 163371},
       metagraph=[('con', 'soc', 'c2s'), ('con', 'var', 'c2v'), ('soc', 'con', 's2c'), ('var', 'con', 'v2c')]),
 tensor([[[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  8.6736e-18,
           -4.7255e+00, -1.7012e+01],
          [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  0.0000e+00,
           -4.7255e+00, -1.7012e+01],
          [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  0.0000e+00,
           -4.7255e+00, -1.7012e+01],
          ...,
          [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  2.3564e-02,
           -4.9864e+00, -1.7951e+01],
          [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  2.7676e-02,
           -4.9864e+00, -1.7951e+01],
          [ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ...,  1.7994e-02,
           -4.9188e+00, -1.7708e+01]]], dtype=torch.float64),
 tensor([[15